# Site settings
title: Offline/Offroad
description: 'A MTB Journal'
url: 'http://offlineoffroad.co.uk' # the base hostname & protocol for your site
twitter_username: benjaminparry
github_username:  benjaminparry

# Build settings
markdown: kramdown
permalink: pretty

repo: https://github.com/offlineoffroad/offlineoffroad.github.io

collections:
 tune-up:
  output: true
  permalink: /:collection/:path/index.html
 rides:
  output: true
  permalink: /:collection/:path/index.html